/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package property;

import java.awt.BasicStroke;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.Dimension;
import java.awt.Component;

import javax.swing.ImageIcon;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;


/**
 *
 * @author Tuan Hien + Hoang Anh
 */
public class Stroke extends javax.swing.JPanel {
    private float strokeWidth = 1f; // kich thuoc net ve mac dinh
    private BasicStroke stroke = new BasicStroke(strokeWidth);
    private float[] dash;
    
    private static final float[] DASH1 =  null;
    private static final float[] DASH2 =  {2f};
    private static final float[] DASH3 =  {5f, 10f};
    private static final float[] DASH4 =  {2f, 4f, 6f, 8f};
    private static final float[] DASH5 = {4f, 4f, 1f};
    public Stroke() {
        initComponents();
        this.setStrokeComboBox();
    }

    public float getStrokeWidth() {
        return strokeWidth;
    }

    public void setStrokeWidth(float strokeWidth) {
        this.strokeWidth = strokeWidth;
    }

    public BasicStroke getStroke() {
        return stroke;
    }

    public void setStroke(float strokeWidth, float[] dash) {
        BasicStroke bsStroke = new BasicStroke(strokeWidth, BasicStroke.CAP_BUTT,
                            BasicStroke.JOIN_BEVEL, 1.0f, dash, 1f);
        this.stroke = bsStroke;
    }

    public float[] getDash() {
        return dash;
    }

    public void setDash(float[] dash) {
        this.dash = dash;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 245, 245));
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Stroke 1", "Stroke 2", "Stroke 3", "Stroke 4", "Stroke 5" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Size:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        
        switch (jComboBox1.getSelectedIndex()) {
            case 0 :
                this.setDash(DASH1);
                this.setStroke(strokeWidth, dash);
                break;
            case 1 : 
                this.setDash(DASH2);
                this.setStroke(strokeWidth, dash);
                break;
            case 2 : 
                this.setDash(DASH3);
                this.setStroke(strokeWidth, dash);
                break;
            case 3 :
                this.setDash(DASH4);
                this.setStroke(strokeWidth, dash);
                break;
            case 4 :
                this.setDash(DASH5);
                this.setStroke(strokeWidth, dash);
                break;
            default: 
                break;
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:  
        this.setStrokeWidth( (float) (jComboBox2.getSelectedIndex() + 1) );
        this.setStroke(strokeWidth, dash);
    }//GEN-LAST:event_jComboBox2ItemStateChanged
    
    // Tao class Hinh anh bieu tuong stroke
    class StrokeComboRenderer extends JLabel implements ListCellRenderer {
        private String fileDashIcon[] = new String[]{"dash1", "dash2", "dash3", "dash4", "dash5"};
        private ImageIcon dashIcon[] = new ImageIcon[5];
        
        public StrokeComboRenderer() {
            setOpaque(true); //Cho phep sua nen doi tuong
            //Dat anh vao giua
            setHorizontalAlignment(CENTER); //Can ngang
            setVerticalAlignment(CENTER); //Can doc
            
            for(int i = 0 ; i < fileDashIcon.length; ++i) {
                dashIcon[i] = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagebutton/" + fileDashIcon[i] + ".png")));
            }
        }
        
        @Override
        public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            if (isSelected) { //Neu da chon doi tuong thi set nen doi tuong duoc chon, con khong tao mac dinh
                setBackground(list.getSelectionBackground());
                setForeground(list.getSelectionForeground());
            }
            else {
                setBackground(list.getBackground());
                setForeground(list.getForeground());
            }
            ImageIcon icon = dashIcon[((Integer) value).intValue()];
            setIcon(icon);
            return this;
        } 
    }
    
    private void setStrokeComboBox() {
        DefaultComboBoxModel dfComboBoxModel = new DefaultComboBoxModel();
        for (int i = 0 ; i < jComboBox1.getItemCount() ; ++i) {
            dfComboBoxModel.addElement(i);
        }
        jComboBox1.setModel(dfComboBoxModel); //Dinh dang kieu comboBox
        
        StrokeComboRenderer renderer = new StrokeComboRenderer();
        renderer.setPreferredSize(new Dimension(86, 30));
        jComboBox1.setRenderer(renderer);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
