/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tool;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Point;
import java.awt.RenderingHints;
import java.awt.geom.AffineTransform;
import java.awt.image.AffineTransformOp;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import shape.DrawType;
import property.Stack;
/**
 *
 * @author admin
 */
public class Replay extends JPanel implements Runnable {

    /**
     * 
     */
    private BufferedImage buff_img,null_img;
    private Image img;
    private int delay = 30;
    private boolean isPlaying;
    private JToggleButton bPlay;
    private Thread thread = null;
    private Graphics2D g2d, g2;
    private Stack stack;
    private int width = 800;
    private int height = 500;
    private int currentImage = 0;
    
    public void setDelay(int delay) {
        this.delay = (105 - delay) / 2;
    }

    public void setButton(JToggleButton bPlay) {
        this.bPlay = bPlay;
    }
    
    public Replay() {
        stack = new Stack();
        isPlaying = false;
        initComponents();
        this.setSize(width, height);
        buff_img = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
        null_img = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
        g2 = (Graphics2D) buff_img.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(new Color(255, 255, 255));
        g2.fillRect(0, 0, buff_img.getWidth(), buff_img.getHeight());
        g2.dispose();
    }
    
    public void startReplay() {
        if (thread == null) {
            refresh();
            thread = new Thread(this);
            isPlaying = true;
            thread.start();
        }
        isPlaying = true;
    }
    
    public void refresh() {
        g2 = (Graphics2D) buff_img.getGraphics();
        g2.drawImage(null_img, 0, 0, null);
        g2.dispose();
        repaint();
    }
    
    public boolean isPlaying() {
        return isPlaying;
    }

    public void setImage(BufferedImage img) {
        buff_img = img;
        g2d = (Graphics2D) buff_img.createGraphics();
        this.setSize(img.getWidth(), img.getHeight());
        this.revalidate();
        this.repaint();
    }

    public BufferedImage getImage() {
        return buff_img;
    }
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        g2 = (Graphics2D) g;
        if (isPlaying) {
            g.drawImage(buff_img, 0, 0, null);
        }
    }

    @Override
    public void run() {
        int increDelay = 60;
        while (currentImage <= stack.getTop()){
            if (isPlaying == false) {
                continue;
            }
            setImage(stack.getImageIndex(currentImage));
            try {
                Thread.sleep(delay * increDelay);
            } catch (InterruptedException ex) {
                System.out.println("error here: replayPanel in run() method");
            }
            repaint();
        }
        System.gc();
        isPlaying = false;
        thread = null;
    }
    
    public BufferedImage getBuffer() {
        return buff_img;
    }
    
    public void dispose() {
        null_img = null;
        buff_img = null;
        g2.dispose();
        g2d.dispose();
        System.gc();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
